package entities;
// Generated Aug 26, 2016 6:11:56 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Alimentos generated by hbm2java
 */
@Entity
@Table(name = "alimentos", catalog = "nutriciondb"
)
public class Alimentos implements java.io.Serializable {

    private Integer codigoAlimento;
    private TipoAlimento tipoAlimento;
    private String descripcionAlimento;
    private String medidaCasera;
    private String medidaCaseraUnidad;
    private double medidaReal;
    private String medidaRealUnidad;
    private double hidratosCarbono;
    private String unidadMedidaHidratosCarbono;
    private double proteina;
    private String unidadMedidaProteina;
    private double grasa;
    private String unidadMedidaGrasa;
    private double sodio;
    private String unidadMedidaSodio;
    private double potasio;
    private String unidadMedidaPotasio;
    private double fosforo;
    private String unidadMedidaFosforo;
    private double calcio;
    private String unidadMedidaCalcio;
    private double hierro;
    private String unidadMedidaHierro;
    private double colesterol;
    private String unidadMedidaColesterol;
    private double purinas;
    private String unidadMedidaPurinas;
    private double fibra;
    private String unidadMedidaFibra;
    private double agua;
    private String unidadMedidaAgua;
    private double calorias;

    public Alimentos() {
    }

    public Alimentos(TipoAlimento tipoAlimento, String descripcionAlimento, String medidaCasera, String medidaCaseraUnidad, double medidaReal, String medidaRealUnidad, double hidratosCarbono, String unidadMedidaHidratosCarbono, double proteina, String unidadMedidaProteina, double grasa, String unidadMedidaGrasa, double sodio, String unidadMedidaSodio, double potasio, String unidadMedidaPotasio, double fosforo, String unidadMedidaFosforo, double calcio, String unidadMedidaCalcio, double hierro, String unidadMedidaHierro, double colesterol, String unidadMedidaColesterol, double purinas, String unidadMedidaPurinas, double fibra, String unidadMedidaFibra, double agua, String unidadMedidaAgua, double calorias) {
        this.tipoAlimento = tipoAlimento;
        this.descripcionAlimento = descripcionAlimento;
        this.medidaCasera = medidaCasera;
        this.medidaCaseraUnidad = medidaCaseraUnidad;
        this.medidaReal = medidaReal;
        this.medidaRealUnidad = medidaRealUnidad;
        this.hidratosCarbono = hidratosCarbono;
        this.unidadMedidaHidratosCarbono = unidadMedidaHidratosCarbono;
        this.proteina = proteina;
        this.unidadMedidaProteina = unidadMedidaProteina;
        this.grasa = grasa;
        this.unidadMedidaGrasa = unidadMedidaGrasa;
        this.sodio = sodio;
        this.unidadMedidaSodio = unidadMedidaSodio;
        this.potasio = potasio;
        this.unidadMedidaPotasio = unidadMedidaPotasio;
        this.fosforo = fosforo;
        this.unidadMedidaFosforo = unidadMedidaFosforo;
        this.calcio = calcio;
        this.unidadMedidaCalcio = unidadMedidaCalcio;
        this.hierro = hierro;
        this.unidadMedidaHierro = unidadMedidaHierro;
        this.colesterol = colesterol;
        this.unidadMedidaColesterol = unidadMedidaColesterol;
        this.purinas = purinas;
        this.unidadMedidaPurinas = unidadMedidaPurinas;
        this.fibra = fibra;
        this.unidadMedidaFibra = unidadMedidaFibra;
        this.agua = agua;
        this.unidadMedidaAgua = unidadMedidaAgua;
        this.calorias = calorias;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "codigo_alimento", unique = true, nullable = false)
    public Integer getCodigoAlimento() {
        System.out.println(Alimentos.class.getSimpleName() + " getCodigoAlimento retorna: " + this.codigoAlimento);
        return this.codigoAlimento;
    }

    public void setCodigoAlimento(Integer codigoAlimento) {
        this.codigoAlimento = codigoAlimento;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tipo_alimento", nullable = false)
    public TipoAlimento getTipoAlimento() {
        System.out.println(Alimentos.class.getSimpleName() + " getTipoAlimento retorna: " + this.tipoAlimento.getCodigoTipoAlimento());
        return this.tipoAlimento;
    }

    public void setTipoAlimento(TipoAlimento tipoAlimento) {
        this.tipoAlimento = tipoAlimento;
    }

    @Column(name = "descripcion_alimento", nullable = false, length = 100)
    public String getDescripcionAlimento() {
        System.out.println(Alimentos.class.getSimpleName() + " getDescripcionAlimento retorna: " + this.descripcionAlimento);
        return this.descripcionAlimento;
    }

    public void setDescripcionAlimento(String descripcionAlimento) {
        this.descripcionAlimento = descripcionAlimento;
    }

    @Column(name = "medida_casera", nullable = false, length = 10)
    public String getMedidaCasera() {
        System.out.println(Alimentos.class.getSimpleName() + " getMedidaCasera retorna: " + this.medidaCasera);
        return this.medidaCasera;
    }

    public void setMedidaCasera(String medidaCasera) {
        this.medidaCasera = medidaCasera;
    }

    @Column(name = "medida_casera_unidad", nullable = false, length = 20)
    public String getMedidaCaseraUnidad() {
        System.out.println(Alimentos.class.getSimpleName() + " getMedidaCaseraUnidad retorna: " + this.medidaCaseraUnidad);
        return this.medidaCaseraUnidad;
    }

    public void setMedidaCaseraUnidad(String medidaCaseraUnidad) {
        this.medidaCaseraUnidad = medidaCaseraUnidad;
    }

    @Column(name = "medida_real", nullable = false, precision = 22, scale = 0)
    public double getMedidaReal() {
        System.out.println(Alimentos.class.getSimpleName() + " getMedidaReal retorna: " + this.medidaReal);
        return this.medidaReal;
    }

    public void setMedidaReal(double medidaReal) {
        this.medidaReal = medidaReal;
    }

    @Column(name = "medida_real_unidad", nullable = false, length = 3)
    public String getMedidaRealUnidad() {
        System.out.println(Alimentos.class.getSimpleName() + " getMedidaRealUnidad retorna: " + this.medidaRealUnidad);
        return this.medidaRealUnidad;
    }

    public void setMedidaRealUnidad(String medidaRealUnidad) {
        this.medidaRealUnidad = medidaRealUnidad;
    }

    @Column(name = "hidratos_carbono", nullable = false, precision = 22, scale = 0)
    public double getHidratosCarbono() {
        System.out.println(Alimentos.class.getSimpleName() + " getHidratosCarbono retorna: " + this.hidratosCarbono);
        return this.hidratosCarbono;
    }

    public void setHidratosCarbono(double hidratosCarbono) {
        this.hidratosCarbono = hidratosCarbono;
    }

    @Column(name = "unidad_medida_hidratos_carbono", nullable = false, length = 3)
    public String getUnidadMedidaHidratosCarbono() {
        System.out.println(Alimentos.class.getSimpleName() + " getUnidadMedidaHidratosCarbono retorna: " + this.unidadMedidaHidratosCarbono);
        return this.unidadMedidaHidratosCarbono;
    }

    public void setUnidadMedidaHidratosCarbono(String unidadMedidaHidratosCarbono) {
        this.unidadMedidaHidratosCarbono = unidadMedidaHidratosCarbono;
    }

    @Column(name = "proteina", nullable = false, precision = 22, scale = 0)
    public double getProteina() {
        return this.proteina;
    }

    public void setProteina(double proteina) {
        this.proteina = proteina;
    }

    @Column(name = "unidad_medida_proteina", nullable = false, length = 3)
    public String getUnidadMedidaProteina() {
        return this.unidadMedidaProteina;
    }

    public void setUnidadMedidaProteina(String unidadMedidaProteina) {
        this.unidadMedidaProteina = unidadMedidaProteina;
    }

    @Column(name = "grasa", nullable = false, precision = 22, scale = 0)
    public double getGrasa() {
        return this.grasa;
    }

    public void setGrasa(double grasa) {
        this.grasa = grasa;
    }

    @Column(name = "unidad_medida_grasa", nullable = false, length = 3)
    public String getUnidadMedidaGrasa() {
        return this.unidadMedidaGrasa;
    }

    public void setUnidadMedidaGrasa(String unidadMedidaGrasa) {
        this.unidadMedidaGrasa = unidadMedidaGrasa;
    }

    @Column(name = "sodio", nullable = false, precision = 22, scale = 0)
    public double getSodio() {
        return this.sodio;
    }

    public void setSodio(double sodio) {
        this.sodio = sodio;
    }

    @Column(name = "unidad_medida_sodio", nullable = false, length = 3)
    public String getUnidadMedidaSodio() {
        return this.unidadMedidaSodio;
    }

    public void setUnidadMedidaSodio(String unidadMedidaSodio) {
        this.unidadMedidaSodio = unidadMedidaSodio;
    }

    @Column(name = "potasio", nullable = false, precision = 22, scale = 0)
    public double getPotasio() {
        return this.potasio;
    }

    public void setPotasio(double potasio) {
        this.potasio = potasio;
    }

    @Column(name = "unidad_medida_potasio", nullable = false, length = 3)
    public String getUnidadMedidaPotasio() {
        return this.unidadMedidaPotasio;
    }

    public void setUnidadMedidaPotasio(String unidadMedidaPotasio) {
        this.unidadMedidaPotasio = unidadMedidaPotasio;
    }

    @Column(name = "fosforo", nullable = false, precision = 22, scale = 0)
    public double getFosforo() {
        return this.fosforo;
    }

    public void setFosforo(double fosforo) {
        this.fosforo = fosforo;
    }

    @Column(name = "unidad_medida_fosforo", nullable = false, length = 3)
    public String getUnidadMedidaFosforo() {
        return this.unidadMedidaFosforo;
    }

    public void setUnidadMedidaFosforo(String unidadMedidaFosforo) {
        this.unidadMedidaFosforo = unidadMedidaFosforo;
    }

    @Column(name = "calcio", nullable = false, precision = 22, scale = 0)
    public double getCalcio() {
        return this.calcio;
    }

    public void setCalcio(double calcio) {
        this.calcio = calcio;
    }

    @Column(name = "unidad_medida_calcio", nullable = false, length = 3)
    public String getUnidadMedidaCalcio() {
        return this.unidadMedidaCalcio;
    }

    public void setUnidadMedidaCalcio(String unidadMedidaCalcio) {
        this.unidadMedidaCalcio = unidadMedidaCalcio;
    }

    @Column(name = "hierro", nullable = false, precision = 22, scale = 0)
    public double getHierro() {
        return this.hierro;
    }

    public void setHierro(double hierro) {
        this.hierro = hierro;
    }

    @Column(name = "unidad_medida_hierro", nullable = false, length = 3)
    public String getUnidadMedidaHierro() {
        return this.unidadMedidaHierro;
    }

    public void setUnidadMedidaHierro(String unidadMedidaHierro) {
        this.unidadMedidaHierro = unidadMedidaHierro;
    }

    @Column(name = "colesterol", nullable = false, precision = 22, scale = 0)
    public double getColesterol() {
        return this.colesterol;
    }

    public void setColesterol(double colesterol) {
        this.colesterol = colesterol;
    }

    @Column(name = "unidad_medida_colesterol", nullable = false, length = 3)
    public String getUnidadMedidaColesterol() {
        return this.unidadMedidaColesterol;
    }

    public void setUnidadMedidaColesterol(String unidadMedidaColesterol) {
        this.unidadMedidaColesterol = unidadMedidaColesterol;
    }

    @Column(name = "purinas", nullable = false, precision = 22, scale = 0)
    public double getPurinas() {
        return this.purinas;
    }

    public void setPurinas(double purinas) {
        this.purinas = purinas;
    }

    @Column(name = "unidad_medida_purinas", nullable = false, length = 3)
    public String getUnidadMedidaPurinas() {
        return this.unidadMedidaPurinas;
    }

    public void setUnidadMedidaPurinas(String unidadMedidaPurinas) {
        this.unidadMedidaPurinas = unidadMedidaPurinas;
    }

    @Column(name = "fibra", nullable = false, precision = 22, scale = 0)
    public double getFibra() {
        return this.fibra;
    }

    public void setFibra(double fibra) {
        this.fibra = fibra;
    }

    @Column(name = "unidad_medida_fibra", nullable = false, length = 3)
    public String getUnidadMedidaFibra() {
        return this.unidadMedidaFibra;
    }

    public void setUnidadMedidaFibra(String unidadMedidaFibra) {
        this.unidadMedidaFibra = unidadMedidaFibra;
    }

    @Column(name = "agua", nullable = false, precision = 22, scale = 0)
    public double getAgua() {
        return this.agua;
    }

    public void setAgua(double agua) {
        this.agua = agua;
    }

    @Column(name = "unidad_medida_agua", nullable = false, length = 3)
    public String getUnidadMedidaAgua() {
        return this.unidadMedidaAgua;
    }

    public void setUnidadMedidaAgua(String unidadMedidaAgua) {
        this.unidadMedidaAgua = unidadMedidaAgua;
    }

    @Column(name = "calorias", nullable = false, precision = 22, scale = 0)
    public double getCalorias() {
        return this.calorias;
    }

    public void setCalorias(double calorias) {
        this.calorias = calorias;
    }

}
