package entities;
// Generated Aug 26, 2016 6:11:56 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PesoIdeal generated by hbm2java
 */
@Entity
@Table(name="peso_ideal"
    ,catalog="nutriciondb"
)
public class PesoIdeal  implements java.io.Serializable {


     private int tallaCm;
     private double edad1516;
     private double edad1719;
     private double edad2024;
     private double edad2529;
     private double edad3039;
     private double edad4049;
     private double edad5059;
     private double edad6069;
     private double contexturaPequenaIni;
     private double contexturaPequenaFin;
     private double contexturaMedianaIni;
     private double contexturaMedianaFin;
     private double contexturaGrandeIni;
     private double contexturaGrandeFin;
     private String sexo;

    public PesoIdeal() {
    }

    public PesoIdeal(int tallaCm, double edad1516, double edad1719, double edad2024, double edad2529, double edad3039, double edad4049, double edad5059, double edad6069, double contexturaPequenaIni, double contexturaPequenaFin, double contexturaMedianaIni, double contexturaMedianaFin, double contexturaGrandeIni, double contexturaGrandeFin, String sexo) {
       this.tallaCm = tallaCm;
       this.edad1516 = edad1516;
       this.edad1719 = edad1719;
       this.edad2024 = edad2024;
       this.edad2529 = edad2529;
       this.edad3039 = edad3039;
       this.edad4049 = edad4049;
       this.edad5059 = edad5059;
       this.edad6069 = edad6069;
       this.contexturaPequenaIni = contexturaPequenaIni;
       this.contexturaPequenaFin = contexturaPequenaFin;
       this.contexturaMedianaIni = contexturaMedianaIni;
       this.contexturaMedianaFin = contexturaMedianaFin;
       this.contexturaGrandeIni = contexturaGrandeIni;
       this.contexturaGrandeFin = contexturaGrandeFin;
       this.sexo = sexo;
    }
   
     @Id 

    
    @Column(name="talla_cm", unique=true, nullable=false)
    public int getTallaCm() {
        return this.tallaCm;
    }
    
    public void setTallaCm(int tallaCm) {
        this.tallaCm = tallaCm;
    }

    
    @Column(name="edad15_16", nullable=false, precision=22, scale=0)
    public double getEdad1516() {
        return this.edad1516;
    }
    
    public void setEdad1516(double edad1516) {
        this.edad1516 = edad1516;
    }

    
    @Column(name="edad17_19", nullable=false, precision=22, scale=0)
    public double getEdad1719() {
        return this.edad1719;
    }
    
    public void setEdad1719(double edad1719) {
        this.edad1719 = edad1719;
    }

    
    @Column(name="edad20_24", nullable=false, precision=22, scale=0)
    public double getEdad2024() {
        return this.edad2024;
    }
    
    public void setEdad2024(double edad2024) {
        this.edad2024 = edad2024;
    }

    
    @Column(name="edad25_29", nullable=false, precision=22, scale=0)
    public double getEdad2529() {
        return this.edad2529;
    }
    
    public void setEdad2529(double edad2529) {
        this.edad2529 = edad2529;
    }

    
    @Column(name="edad30_39", nullable=false, precision=22, scale=0)
    public double getEdad3039() {
        return this.edad3039;
    }
    
    public void setEdad3039(double edad3039) {
        this.edad3039 = edad3039;
    }

    
    @Column(name="edad40_49", nullable=false, precision=22, scale=0)
    public double getEdad4049() {
        return this.edad4049;
    }
    
    public void setEdad4049(double edad4049) {
        this.edad4049 = edad4049;
    }

    
    @Column(name="edad50_59", nullable=false, precision=22, scale=0)
    public double getEdad5059() {
        return this.edad5059;
    }
    
    public void setEdad5059(double edad5059) {
        this.edad5059 = edad5059;
    }

    
    @Column(name="edad60_69", nullable=false, precision=22, scale=0)
    public double getEdad6069() {
        return this.edad6069;
    }
    
    public void setEdad6069(double edad6069) {
        this.edad6069 = edad6069;
    }

    
    @Column(name="contextura_pequena_ini", nullable=false, precision=22, scale=0)
    public double getContexturaPequenaIni() {
        return this.contexturaPequenaIni;
    }
    
    public void setContexturaPequenaIni(double contexturaPequenaIni) {
        this.contexturaPequenaIni = contexturaPequenaIni;
    }

    
    @Column(name="contextura_pequena_fin", nullable=false, precision=22, scale=0)
    public double getContexturaPequenaFin() {
        return this.contexturaPequenaFin;
    }
    
    public void setContexturaPequenaFin(double contexturaPequenaFin) {
        this.contexturaPequenaFin = contexturaPequenaFin;
    }

    
    @Column(name="contextura_mediana_ini", nullable=false, precision=22, scale=0)
    public double getContexturaMedianaIni() {
        return this.contexturaMedianaIni;
    }
    
    public void setContexturaMedianaIni(double contexturaMedianaIni) {
        this.contexturaMedianaIni = contexturaMedianaIni;
    }

    
    @Column(name="contextura_mediana_fin", nullable=false, precision=22, scale=0)
    public double getContexturaMedianaFin() {
        return this.contexturaMedianaFin;
    }
    
    public void setContexturaMedianaFin(double contexturaMedianaFin) {
        this.contexturaMedianaFin = contexturaMedianaFin;
    }

    
    @Column(name="contextura_grande_ini", nullable=false, precision=22, scale=0)
    public double getContexturaGrandeIni() {
        return this.contexturaGrandeIni;
    }
    
    public void setContexturaGrandeIni(double contexturaGrandeIni) {
        this.contexturaGrandeIni = contexturaGrandeIni;
    }

    
    @Column(name="contextura_grande_fin", nullable=false, precision=22, scale=0)
    public double getContexturaGrandeFin() {
        return this.contexturaGrandeFin;
    }
    
    public void setContexturaGrandeFin(double contexturaGrandeFin) {
        this.contexturaGrandeFin = contexturaGrandeFin;
    }

    
    @Column(name="sexo", nullable=false, length=1)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }




}


