package entities;
// Generated Aug 26, 2016 6:11:56 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoAlimento generated by hbm2java
 */
@Entity
@Table(name = "tipo_alimento", catalog = "nutriciondb"
)
public class TipoAlimento implements java.io.Serializable {

    private Integer codigoTipoAlimento;
    private String descripcionTipoAlimento;
    private Set alimentoses = new HashSet(0);

    public TipoAlimento() {
    }

    public TipoAlimento(String descripcionTipoAlimento) {
        this.descripcionTipoAlimento = descripcionTipoAlimento;
    }

    public TipoAlimento(String descripcionTipoAlimento, Set alimentoses) {
        this.descripcionTipoAlimento = descripcionTipoAlimento;
        this.alimentoses = alimentoses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "codigo_tipo_alimento", unique = true, nullable = false)
    public Integer getCodigoTipoAlimento() {
        return this.codigoTipoAlimento;
    }

    public void setCodigoTipoAlimento(Integer codigoTipoAlimento) {
        this.codigoTipoAlimento = codigoTipoAlimento;
    }

    @Column(name = "descripcion_tipo_alimento", nullable = false, length = 100)
    public String getDescripcionTipoAlimento() {
        return this.descripcionTipoAlimento;
    }

    public void setDescripcionTipoAlimento(String descripcionTipoAlimento) {
        this.descripcionTipoAlimento = descripcionTipoAlimento;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoAlimento")
    public Set getAlimentoses() {
        return this.alimentoses;
    }

    public void setAlimentoses(Set alimentoses) {
        this.alimentoses = alimentoses;
    }

}
